### ISSUE TITLE
More permissive license

### ISSUE THREAD

**Issue by felixriese** [spectralpython/spectral#103]
I have imported the `spectral` package into my code because it works great and is easy to use. It is a processing script of hyperspectral data, which I want to provide as open-source software here on GitHub. I want to provide it with a very permissive license, meaning MIT or BSD-3-Clause. With the GNU GPL2 licensed `spectral` package as import, this is not possible as far as I see it.

Can you please
a) change the license of `spectral` to a more permissive license such as MIT or BSD-3-Clause, or
b) give me permission to use your `spectral` package in my repository?

If not, please let me know. I think this is important information for every user of your package.

Thank you very much in advance!

**Comment by tboggs** [comment]
Hi Felix,

I've actually been considering migrating to the MIT license. I just need to finish a few other updates first and check with some contributors. You have my permission to use the package in your repository.

Regards,
Thomas

**Comment by tboggs** [comment]
@donm , you have some significant code contributions - is it ok with you if the license gets changed to MIT? I've been considering this for a while. Several people (including myself) have had issues integrating the package with other projects that have more permissive licenses.

**Comment by donm** [comment]
Sure, that's fine.  

Racket just went through a [similar license change](https://github.com/racket/racket/issues/1570) and they decided to dual-license under the [Apache License (version 2)](https://opensource.org/licenses/Apache-2.0), and the [MIT license](https://opensource.org/licenses/MIT).  I don't know if that's overkill for this project or not, but the issue has their reasons and the specific wording that they asked contributors to use when agreeing to change the license.

**Comment by tboggs** [comment]
Dual-licensing is probably overkill here. I don't see patent protection being a major issue so the MIT license should be fine. Thanks for the quick reply.

**Comment by tboggs** [comment]
@lewismc I've migrated `spectral` to the MIT license (currently on the mit-license branch). It appears that the license text on the Anaconda license badge on the README needs to be changed on the Anaconda [spectral site](https://anaconda.org/conda-forge/spectral) to reflect the change in GitHub. Could you take care of making that change? I don't think I have an account over there.

**Comment by lewismc** [comment]
@tboggs I'll try to get to this tomorrow yes. Thanks

**Comment by lewismc** [comment]
@tboggs you need to check for other occurences of GPL ort any other licenses. For example, see https://github.com/spectralpython/spectral/blob/mit-license/setup.py#L29

**Comment by lewismc** [comment]
Here you go @tboggs let's track the recipe 

https://github.com/conda-forge/spectral-feedstock/pull/4

**Comment by tboggs** [comment]
@lewismc good catch. I removed license headers from individual source files, changed the LICENSE file, and changed the trove classifiers but missed those two spots. Web site documentation is ready to go.

To avoid having the repo in a mixed state, I'll get the release ready, then accept your merge request just before merging and tagging the updated spectral repo (likely tomorrow).

Thanks again.

**Comment by lewismc** [comment]
@tboggs I pushed another commit to the feedstock... I hope this resolves the issue.
This one became a bit of a PITA but thanks for your patience. 👍

**Comment by kormang** [comment]
Should this issue be closed?
