### ISSUE TITLE
Kmeans processing of spectral.io.bipfile.BipFile versus numpy array

### ISSUE THREAD

**Issue by pythonic2020** [spectralpython/spectral#119]
Hello, I have a msam result (7 bands, default float64 array) that I want to run kmeans classification on.  I need to run np.nan_to_num() on the file before applying kmeans.  It works fine and terminal/notebook output looks like this:  

```
spectral:INFO: k-means iteration 1 - 999998 pixels reassigned.
INFO:spectral:k-means iteration 1 - 999998 pixels reassigned.
spectral:INFO: k-means iteration 2 - 128415 pixels reassigned.
INFO:spectral:k-means iteration 2 - 128415 pixels reassigned.
spectral:INFO: k-means iteration 3 - 127319 pixels reassigned.
INFO:spectral:k-means iteration 3 - 127319 pixels reassigned.
...
```

I want to save the msam result to disk before the kmeans processing, to save time.  To save, I used:

```
outfilename = 'msam_result.hdr'
envi.save_image(outfilename, cube_msam, dtype=np.float64, force=True)
```

When I read that file back in to run kmeans on it, I use this code:

```msam_result_envi = envi.open('msam_result.hdr', image='msam_result.img')```

Result is a BipFile.  Here are the metadata:

```
Data Source:   '.\msam_result.img'
	# Rows:           1000
	# Samples:        1000
	# Bands:             7
	Interleave:        BIP
	Quantization:  64 bits
	Data format:   float64
```

When I try to run Kmeans on it, I get this terminal output:

`Iteration 1...  0.Iteration 1...  0.Iteration 1...  0.Iteration 1...  0.Iteration 1...  0.Iteration 1...  0.Iteration 1...  0.Iteration 1...  0.Iteration 1...  0.Iteration 1...  0.Iteration 1...  0.Iteration 1...  1.Iteration 1...  1.Iteration 1...  1.Iteration 1...  1.Iteration 1...  1.Iteration 1...  1.Iteration 1...  1.Iteration 1...  1.Iteration 1...  1.Iteration 1...  1.Iteration 1...  2.Iteration 1...  2.Iteration 1...  2.Iteration 1...  2.Iteration 1...  2.Iteration 1...  2.Iteration 1...  2.Iteration 1...  2.Iteration 1...  2.Iteration 1...  2.Iteration 1...  3.Iteration 1...  3.Iteration 1...  3.Iteration 1...  3.Iteration 1...  3.Iteration 1...  3.Iteration 1...  3.Iteration 1...  3.Iteration 1...  3.Iteration 1...  3.Iteration 1...  4.Iteration 1...  4.Iteration 1...  4.Iteration 1...  4.Iteration 1`

The processing takes too long, and I kill it each time, but it seems to be working.  What am I doing wrong here?  Do I need to alter the data type or band interleaving of the BipFile, or convert it to an array, before running Kmeans on it?  Sorry to trouble you, and thank you in advance...

**Comment by tboggs** [comment]
`BipFile` (a subclass of `SpyFile`) is just an interface to the image data file and accessing the data that way repetitively is very slow because it will keep reading data from disk every time the same data are needed. It will be much faster if you read that data to memory instead:

    msam_result_envi = envi.open('msam_result.hdr', image='msam_result.img').load()

**Comment by pythonic2020** [comment]
Oh for heaven's sake.  I thought it could be something silly like that.  I'll try that now.  Thank you very much!!!!!!!!!!!!!!!!!!!!

**Comment by pythonic2020** [comment]
That works perfectly, but I noticed that when I read in the data using .load(), it came in as float32 rather than float64 (double-precision), the format in which it was saved.  The saved envi header reads "data type=5" which is float64.  Any ideas?  Did the .load() function automatically, such as by using the scale keyword:

```
scale (bool, default True):

Specifies whether any applicable scale factor should be applied to the data after loading.
```

**Comment by tboggs** [comment]
By default, images are loaded as 32-bit float arrays. You can pass an optional "dtype" keyword to the load method.

**Comment by pythonic2020** [comment]
Got it.  Many thanks!
