### ISSUE TITLE
view_cube image returns only top image and no other bands 

### ISSUE THREAD

**Issue by npucino** [spectralpython/spectral#122]
When I run ` view_cube(img, bands=[1, 12, 2])`, the returned interactive cube correctly display the top image but misses all the other bands, displaying all white in the z dimension.

![image](https://user-images.githubusercontent.com/44853536/112710187-577ea400-8f13-11eb-9b04-0509512b8402.png)
my image details:

`Data Source:   'C:\test_hsi\multi_1_rd_rf_or'
	# Rows:            860
	# Samples:        3600
	# Bands:           272
	Interleave:        BSQ
	Quantization:  32 bits
	Data format:   float32`

**Comment by tboggs** [comment]
That is odd. Can you tell me the min and max data values for the image cube?

**Comment by npucino** [comment]
Thanks for the prompt reply.
Here is the result:
`0.0 1.017753`
`0.0 1.1102917`

**Comment by npucino** [comment]
SOLVED.
![image](https://user-images.githubusercontent.com/44853536/112788941-b5dc8b80-90a7-11eb-8eb7-3e0df0759456.png)

Sorry it was a banal problem.
My image data boundaries were all zeroes. In other words, the image was not cropped to valid data only. By reading only a subset of the cube where the boudaries are all valid, with:

`img_sub=img.read_subregion((200,650),(2400,2850))`

when running:

`view_cube(img_sub, bands=[1, 12, 2])`

displayed the z dimension correctly.

Thanks for this package!
Nick
