### ISSUE TITLE
Spectral/PPI is not running properly

### ISSUE THREAD

**Issue by Ridhee** [spectralpython/spectral#125]
Hii

![ppi problem](https://user-images.githubusercontent.com/84409371/119258409-222ac580-bbe7-11eb-9c87-1d93500e268a.PNG)
 I am getting this while running the function.

Can anyone please tell me how to solve this problem?

**Comment by tboggs** [comment]
`ppi` expects a numpy array as input so instead, you should do
```
data = img.load()
```
and pass `data` to the `ppi` function.

**Comment by Ridhee** [comment]
Thank you. It is working now.
