### ISSUE TITLE
envi file containing complex values

### ISSUE THREAD

**Issue by Nipouradar1995** [spectralpython/spectral#135]
hello 
I've  just started to work with SPy to read envi files which contains complex values ,after runing this code
![1](https://user-images.githubusercontent.com/102966489/161548078-ccefa65b-6e31-4334-a001-02bce224ca52.png)
i got this parameter 
![2](https://user-images.githubusercontent.com/102966489/161549037-a821cc60-43b9-4218-9d8b-638ac7aab62d.png)
all seems okey because my envi header file is : dtype=6  which refer to 32*2 complex
![3](https://user-images.githubusercontent.com/102966489/161549141-50b294e0-c432-43bf-a2a9-a8cd6108a6cc.png)
but when i checked the values of the array i noticed that it contains just the real parts and the complex part is 0   
![5](https://user-images.githubusercontent.com/102966489/161549717-24441ef1-2c5e-44f3-bc18-b75cb71d92a7.png)
which is different from what i got with IDL , here is some values of the first column which contain  real and imaginary part 
![6](https://user-images.githubusercontent.com/102966489/161550012-5461e5dd-0034-495c-ac1c-c7f1633c4fa4.png)
so there is something wrong on my code or SPy dont support the files which contains complex value.
thanks in advance .

**Comment by tboggs** [comment]
I've never processed complex images with SPy but it seems like it should be possible. What happens if you modify your code to replace `img.load()` with `img.load(dtype=np.csingle)`?

**Comment by Nipouradar1995** [comment]
thank you a lot ... it works with your modification .

**Comment by tboggs** [comment]
Great. I'll update the code so the correct dtype is automatically used for complex data types.
