### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by TouchTheFishy** [spectralpython/spectral#136]
Hi!

Just wanted to let you know (in case you didn't already) that there is a deprecation warning:
```
/home/bota/.local/lib/python3.8/site-packages/spectral/io/envi.py:684: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  fout.write(data.tostring())
```

Cheers
Fishy

**Comment by tboggs** [comment]
Thanks. I thought I updated all of those but it appears I missed a few.
