### ISSUE TITLE
Combination of USGS and ECOSTRESS database/spectral library

### ISSUE THREAD

**Issue by Tidomann** [spectralpython/spectral#138]
I'm able to create a DB from both ecostress and usgs files and output an envi spectral library for each.

Is it possible to merge the two databases or the envi spectral libraries?

I can imagine a possibility of trying to match the two database schemas and tailoring the import and export functions to work but I was wondering if there is a simpler method.

I'm not as familiar with envi spectral libraries- is there a good way of combining the two outputs?

**Comment by tboggs** [comment]
I don't think there's an easy way to combine the two databases. If you created your ENVI spectral libraries using the `create_envi_spectral_library` method and used the same `bands` argument for both libraries, then you could just hack them together by modifying the `metadata`, `names`, and `spectra` attributes of one of the libraries (i.e., by combining it with the values from the other library).
