### ISSUE TITLE
Color Space Explorer becomes unresponsive after using Decorrelation Stretch Renderer,

### ISSUE THREAD

**Issue by aloboa** [spectralpython/spectral#141]
After using Decorrelation Stretch Renderer, Color Space Explorer becomes
unresponsive (you click the different options but the display is not updated).
Opening the Raster Layer Styling works, and then the Color Space Explorer works as well.

**Comment by tboggs** [comment]
Are you sure you are in the right repo? I don't see a Decorrelation Stretch Renderer, Color Space Explorer, or Raster Layer Styling here.

**Comment by aloboa** [comment]
oops, sorry, wrong repo
