### ISSUE TITLE
data type 'complex256' not understood

### ISSUE THREAD

**Issue by aaronfultonnz** [spectralpython/spectral#144]
There was a bug introduced with #135 relating to complex data types on windows.

Windows does not have the complex256 dtype which causes this line to fail:

Line 199 in io/spyfile.py
`ctypes = [np.dtype(f'complex{b}').name for b in (64, 128, 256)]`

here are some examples of how other projects have solved this issue:
https://www.programcreek.com/python/example/125383/numpy.complex256

**Comment by tboggs** [comment]
Thanks for the bug report. Will get this fixed shortly.
