### ISSUE TITLE
`EcostressDatabase` imports `Instrument` field incorrectly

### ISSUE THREAD

**Issue by MattWenham** [spectralpython/spectral#146]
Due to a change in the filename format, `EcostressDatabase` currently imports the `Instrument` field incorrectly. The fix would appear to be to change line 197 of `ecostress.py` to read:

    instrument = os.path.basename(f).split('.')[-3]

My apologies, I can't put this into a PR as my employer does not allow me to contribute to Open Source projects 😕

**Comment by tboggs** [comment]
Thanks for the suggested fix. With which version of Ecostress did you encounter this?

**Comment by MattWenham** [comment]
Appears to be v1.0, the current version: https://speclib.jpl.nasa.gov/
