### ISSUE TITLE
Impossible to open ENVI spectral library

### ISSUE THREAD

**Issue by AntanisMJR** [spectralpython/spectral#161]
Hi, 
I'm trying to use Spectral to open an ENVI spectral library.

As a consequence of some prior processing, I have two formats for the header file:

![Screenshot 2023-10-27 160115](https://github.com/Quasars/orange-spectroscopy/assets/74669111/baba7436-d131-48c2-9d7b-1866d0e9e82c)

Other  header for same file 
![Screenshot 2023-10-27 160248](https://github.com/Quasars/orange-spectroscopy/assets/74669111/8ffa0b85-a8ed-4ae9-8fa1-c597a3aae520)

The code that I am using:

`import matplotlib
matplotlib.use('WX')
import spectral as sp1
import pandas as pd

SpecLib = sp1.envi.open("C:/mypath/file_name.hdr")
SpecLib = pd.DataFrame(index=SpecLib.names, data=SpecLib.spectra, columns=SpecLib.bands.centers)

print(index)
print(data)
print(columns)`

The errors I get:
Traceback (most recent call last):
  File "C:\Users\Utente\anaconda3\envs\library_converter\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-2c2e0aaa397f>", line 1, in <module>
    runfile('C:\\*\\Correlograms\\Envi_bsq_numpy_to_csv.py', wdir='C:\\*\\SPECTRAL_Process\\Correlograms')
  File "C:\Program Files\JetBrains\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2023.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\*\Envi_bsq_numpy_to_csv.py", line 7, in <module>
    SpecLib = pd.DataFrame(index=SpecLib.names, data=SpecLib.spectra, columns=SpecLib.bands.centers)
AttributeError: 'BsqFile' object has no attribute 'names'

Thanks a lot for the help!

**Comment by tboggs** [comment]
If you want your first file header to be loaded as a spectral library (which will populate the "names" attribute of the returned object), then you should change the "file type" parameter in the header to this:

```
file type = ENVI Spectral Library
```

**Comment by AntanisMJR** [comment]
Thanks a lot for the answer! How can I also save a new spectral library from the pandas dataframe?
