### ISSUE TITLE
Add spectralpython to gitter.im

### ISSUE THREAD

**Issue by kidpixo** [spectralpython/spectral#47]
It could be a good idea to discuss features, instead opening a new issue for everything.

It is an automated process, see [Gitter](https://gitter.im/dbcli/pgcli)

**Comment by tboggs** [comment]
Sounds fine to me for initial discussions. I added a `spectralpython` room on gitter but when I tried to add you, it said "forbidden". Do you need to be a member of the `spectralpython` community to get access to the room?

**Comment by kidpixo** [comment]
Uhm not that I am aware of... link? 
https://gitter.im/spectralpython/spectral results in a `404`

Did you put a badge on the README?

**Comment by kidpixo** [comment]
Ok, I found your account at  https://gitter.im/orgs/spectralpython/rooms. From my account, it  seems you didn't create rooms.

**Comment by tboggs** [comment]
I created a room from the repo: [https://gitter.im/spectralpython/spectral](https://gitter.im/spectralpython/spectral).

Can you see it now?

**Comment by kidpixo** [comment]
Ok, it depends which kind of rooms you created, see [Gitter rooms – Gitter](https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-rooms).

**Comment by tboggs** [comment]
Gitter room is created ([https://gitter.im/spectralpython/spectral](https://gitter.im/spectralpython/spectral)) and badge added to README so I'm closing this issue.
