### ISSUE TITLE
Can't open .hdf ( binary file ) from ASTER 1T

### ISSUE THREAD

**Issue by brunorpinho** [spectralpython/spectral#52]
First, I would like to thank you for this great code!

My problem is that I can't open an ASTER image (.hdf) with the open_image function. Am missing something? Not supported? Do I need to process the file before?

Thanks

**Comment by tboggs** [comment]
No, you didn't miss anything. HDF is a general format and the `spectral` module does not recognize HDF or any particular formats that use it (like HDF-EOS). To read ASTER data, there are a few options. You could use an HDF module (like [h5py](http://www.h5py.org/)) to read the image data into an `ndarray`. If need to retain the image metadata, you could use [this tool](http://newsroom.gsfc.nasa.gov/sdptoolkit/HEG/HEGHome.html) to convert the HDF to GeoTiff, then use gdal_translate to convert the GeoTiff to ENVI format, which the `spectral` module will recognize.

**Comment by brunorpinho** [comment]
Thank you @tboggs ! I will just have to calculate Surface Reflectance and Emissivity before importing it into `spectral`, right?
