### ISSUE TITLE
mnf documentation examples use invalid call signature

### ISSUE THREAD

**Issue by tboggs** [spectralpython/spectral#59]
In the following lines of the `spectral.mnf` doc string, `data` should be added as the first argument:

    >>> denoised = mnfr.denoise(snr=10)

    >>> # Reduce dimensionality, retaining NAPC components where SNR >= 10.
    >>> reduced = mnfr.reduce(snr=10)

    >>> # Reduce dimensionality, retaining top 50 NAPC components.
    >>> reduced = mnfr.reduce(num=50)

**Comment by aloboa** [comment]
Confirm it works with e.g
denoised = mnfr.denoise(data,snr=10)
