### ISSUE TITLE
Problem in classification.

### ISSUE THREAD

**Issue by Pruthvi3796** [spectralpython/spectral#65]
```
from spectral import *
#M is the image dataset(ndarray of hsi cube of shaoe(210,370L,425L))
#n2 is the spectral library(16 spectra) of shape(16L,425L)425 bands.
cla=spectral_angles(M,n2)
clmap=np.argmin(cla,2)
classes=(clmap+1)
v=spy.imshow(classes=(clmap+1))
```
but it does not show unclassified region.It classified all the image(misclassification).
Produce the following result.Also I don't know how to set threshold?
![c](https://cloud.githubusercontent.com/assets/26962711/25303830/4e784e62-2778-11e7-9ff1-96314f1b11df.png)

**Comment by tboggs** [comment]
I don't know what you mean by "unclassified region". You appear to be classifying every pixel so there is no unclassified region.

If you want to set the class of pixels above some threshold to zero, you could do that like this:

    clmap = clmap + 1
    threshold = 0.1
    clmap[np.min(cla, -1) > threshold] = 0

**Comment by Pruthvi3796** [comment]
When i am classifying same image in ENVI it gives the following result.
![ENVI Result](https://cloud.githubusercontent.com/assets/26962711/25310685/11d313ee-2808-11e7-9602-b80354257013.PNG)
This result is also verified with grount truth point data.In this black region is unclassified region.where as in python result(show in first image) does not show unclassified region.Cyan color is classified as class:6 cotton.So what is the problem.

**Comment by tboggs** [comment]
I still do not know what you mean by "unclassified region". Are those pixels you don't want classified or pixels whose minimum spectral angle is above some threshold?

**Comment by Pruthvi3796** [comment]
Thanks tboggs for Reply.Now it is coming correct.Now the Question is the how to set the projection to the classified image same as the unclassfied image in save_classification?

**Comment by tboggs** [comment]
See the documentation for `save_classification`. It accepts an optional "metadata" keyword (whose value is a `dict`), which can include metadata from the original image (i.e., from the `metadata` attribute of the source image). So you could do

    spy.envi.save_classification('results.hdr', classes, metadata=src_image.metadata)

or create a new dict with only a subset of key-value pairs from `src_image.metadata`.
