### ISSUE TITLE
Open ENVI file

### ISSUE THREAD

**Issue by prkyprky** [spectralpython/spectral#72]
Hi, when I try open ENVI file (in .pix format) by spectral, image is broken. After loading is image defected like this. My code is really simply, but it doesnt work. Original image is aerial image. Could you please help me? 

Thank you

```
from spectral import *

file_hdr = 'data/CASI_2017_05_18_120034.cc.dc.sl.fss.so.rc.sc.rY_g.pix.hdr'
CASI_op = envi.open(file_hdr)
CASI = CASI_op.open_memmap(writeable=True)

```
![snimek obrazovky porizeny 2018-02-13 15-38-27](https://user-images.githubusercontent.com/15195671/36155206-0385b660-10d4-11e8-8a0e-fd1db4baaa8c.png)

**Comment by tboggs** [comment]
Can you post the contents of the .hdr file and the output of `CASI_op.shape`?

**Comment by prkyprky** [comment]
Sure. In .hdr file is: 

> ENVI
> description = {
>     Image File: ../pix_files/CASI_2017_05_18_120034.cc.dc.sl.fss.so.rc.sc.rY.rad_g.pix, created by geocor V:5.6.3 (A) [2017/11/02 15:13:29] }
> samples = 3646
> lines   = 4934
> bands   = 48
> header offset = 82432
> file type   = PCI
> data type   = 12
> interleave  = BIP
> sensor type = Unknown
> byte order  = 1
> read procedures = {pci_read_spatial, pci_read_spectral}
> map info = { UTM, 1, 1, 321711.200, 5561737.600,    0.80,    0.80, 33, North, WGS-84 }
> pixel size = {   0.800,    0.800, units=meters }

(I skiped band names, fwhm and wavelength)

and output of `CASI_op.shape` is: 

> (4934, 3646, 48)

Thank you.

**Comment by tboggs** [comment]
I could be wrong here but it looks like that is just how the image data are formatted, perhaps for convenient display puposes. The header states that there are 4934 rows and 3646 columns, whereas the flightline itself has an aspect ration of around 10:1. What is the output of `CASI_op[50, 50]`?

**Comment by prkyprky** [comment]
It depend. In our case, we are using lot of different shapes of flightline. This is relatively short and with angle 45°. Around flight line is image filled by zeroes for creating bbox. 
Output of CASI_op[50,50] is: 
CASI_op[100,100]
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=uint16) 

Size of image is: 1.7 GB and 2676.8m x 3947.2m

Original image is this:
![snimek obrazovky porizeny 2018-02-14 09-50-44](https://user-images.githubusercontent.com/15195671/36195087-8ff4b162-116c-11e8-9b73-0df101bb4c58.png)

**Comment by prkyprky** [comment]
Hi, I tried it and it doesnt work, I tried to determinate where is appended some data and I couldnt find it. I also tried remove read procedures and it also doesnt work.

**Comment by tboggs** [comment]
Removing `read_procedures` from the header won't help. My point was that `read_procedures` specifies custom IDL scripts used by ENVI for reading the data (i.e., it is not a standard ENVI data file).

Can you tell me the exact file size, in bytes? It should be 10 digits long.

**Comment by prkyprky** [comment]
Ok, I'sorry. Exact size of pix file is 1729062400 and hdr file

**Comment by tboggs** [comment]
It doesn't look like there is a fixed amount of padding per image row; otherwise, it would probably be possible to adjust the `samples` parameter of the header to display the data properly. Unfortunately, I haven't found any documentation on how to read PCI data files. I'll see if I can find IDL scripts for `pci_read_spatial`, `pci_read_spectral`. If I can't find that soon, there should probably be an update for `envi.open` to raise an exception whenever the header has `file type = PCI`.

While the visual display is warped, it looks like you could still do spectral processing on the file by generating a mask from any of the bands, since non-image pixels are all zeros.

**Comment by prkyprky** [comment]
I solved this problem. Now I tried edit HDR file manualy and I changed line 'samples'. If I change number and add  + 2 then image after loading and saving by Spectral is OK. Later I will test it with more images. Thank you so much for help.
