### ISSUE TITLE
unable to open .hdr file

### ISSUE THREAD

**Issue by BlcaKHat** [spectralpython/spectral#73]
as the optional `image` argument to envi.open.
>>> img = envi.open('EO1H1400432009124110PY.hdr', 'EO1H1400432009124110PY.hdr')
Unable to create memmap interface.
>>>

**Comment by BlcaKHat** [comment]
i am able to open .lan, .spc but when i am opening .hdr , it's giving error. I am new to it, please help.

**Comment by tboggs** [comment]
It is not an error per se. It is just informing you that numpy was not able to create a memmap interface to the file, which will result it significantly slower performance.

What is the size of the file (and also the sizes of the files that opened successfully)? Are you on a 32 or 64-bit system?

**Comment by BlcaKHat** [comment]
i am on 64 bit system and i want to open an image generated by envy . with the help of python.
I want to open the image same as it open in envi. please suggest me some libraries which will help me.
https://drive.google.com/open?id=1d4Zdc4RdB38v6EQtQHl7u6DbHegItcfq
these are the images of my file and what i want to do. I am new to it and my supervisor gave me this work. please help

**Comment by tboggs** [comment]
In your original post, you have the header file passed as the argument to `envi.open` twice (both arguments end in ".HDR"). The second argument should be the name of the image data file, which should either have a different extension (e.g., ".img", ".ref") or no extension at all.

**Comment by tboggs** [comment]
There are multiple examples in the [online documentation](http://www.spectralpython.net/graphics.html) and system requirements are detailed in the [installation section](http://www.spectralpython.net/installation.html).

**Comment by BlcaKHat** [comment]
I got it now. thank you so much. It was a small mistake. I lost the flow. thanx for your support.

**Comment by tboggs** [comment]
You are welcome.
