### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous.  Use a.any() or a.all()

### ISSUE THREAD

**Issue by BlcaKHat** [spectralpython/spectral#76]
I am  facing this error while running GUI with spectral.
Traceback (most recent call last):
  File "D:\llfg\hrs\RS Datasets Viewer\OpenImage.py", line 150, in browse
    while wi < (self.width) and zero==0:
ValueError: The truth value of an array with more than one element is ambiguous.
 Use a.any() or a.all()

**Comment by tboggs** [comment]
This is a general python issue. It appears you are trying to make a boolean comparison with a variable that is a numpy array (`wi`, `zero`, or `self.width`). Do a web search for the text of your error and you should find plenty of results.

**Comment by BlcaKHat** [comment]
I tried my best . if you can try, I will upload the code.
