### ISSUE TITLE
how do i display the number of bands in my .hdr file ?

### ISSUE THREAD

**Issue by BlcaKHat** [spectralpython/spectral#77]
I want o see all the bands present in my .hdr file. and I want to open it individually.
I know it's like a direct question but I am not able to do it.

**Comment by tboggs** [comment]
If there is band information in the header then it will be in the `bands` attribute of the opened file (e.g., `image.bands`). The `bands` attribute is an instance of a [BandInfo](http://www.spectralpython.net/class_func_ref.html#spectral.BandInfo) object.

If you want to read an entire band, use `image.read_band`. You can pass the result of that to `imshow`.
