### ISSUE TITLE
what are all these metric in image.

### ISSUE THREAD

**Issue by BlcaKHat** [spectralpython/spectral#80]
when i open an image to visualise, what is the scale metric. how do i change it ?.
I just want to open the image. 
suggestion please.
https://drive.google.com/open?id=1YHLSd1ZYtpkljzGOnwhQHrjLrlQnKD51

**Comment by tboggs** [comment]
When `spectral.imshow` is called, the entire image extent is displayed. The standard `matplotlib.imshow` tools are used to to pan/zoom the image. Click on the tool button with 4 arrows (at the bottom of the window), then click & drag with the right or left mouse button to pan & zoom.

**Comment by BlcaKHat** [comment]
![asd1](https://user-images.githubusercontent.com/16970999/38244805-65a2aa6e-3759-11e8-8b42-9e0b94009c93.png)

I want to remove the scaling on left and down . how do i do that >? the pen highlighted area

**Comment by tboggs** [comment]
Images are rendered using matplotlib so you can use matplotlib functions to disable the tick labels.

**Comment by tboggs** [comment]
You can create the matplotlib figure explicitly, then pass the "fignum" keyword to `spectral.imshow` so it will render to that figure. Then, there are multiple ways to modify the tick labels. For example, see [here](https://stackoverflow.com/questions/25124143/matplotlib-subplots-get-rid-of-tick-labels-altogether), [here](https://stackoverflow.com/questions/23618733/python-matplotlib-how-to-plot-in-a-subplot-with-ticks-but-no-tick-labels), or [here](https://stackoverflow.com/questions/40918922/set-tick-labels-in-matplotlib).

**Comment by BlcaKHat** [comment]
I am not able to do it . can I expect more help. ?

**Comment by jkibele** [comment]
The metrics are just the number of pixels. You can make them go away with one additional line of code.

```python
ax = imshow(image)
ax.axes.set_axis_off()
```

[Here](https://gist.github.com/jkibele/058a90c4af32515770b904a8a9c8cdcf) is a working example. This is standard matplotlib functionality, so for more information you can refer to the [matplotlib documentation](https://matplotlib.org/index.html).

**Comment by BlcaKHat** [comment]
thanx jkibele. this worked for me.
