### ISSUE TITLE
Error while performing MNF.

### ISSUE THREAD

**Issue by BlcaKHat** [spectralpython/spectral#82]
I am trying for MNF as suggested in the example. but it need two params  (only one is given.)

![mnf](https://user-images.githubusercontent.com/16970999/38548816-548bb58c-3cd0-11e8-8417-a014b339550e.png)

**Comment by tboggs** [comment]
That is a typo in the web site documentation. The first argument to `denoise` should be the data to be denoised. The doc string for the `denoise` method describes the arguments correctly. The same is true for the `reduce` method.

**Comment by BlcaKHat** [comment]
I was checking the result with ENVI result (MNF Rotation -> forward rotation ->Estimate Noise Statistics from data .)
The results are little different. I don't no if they are same process. 
Suggest me something.

**Comment by donm** [comment]
Keep in mind, it can't be assumed with 100% certainty that all ENVI algorithms are optimal, standard, or even correct. For example, the ENVI implementation of ACE was incorrect until version 5.2.

Also, not having the ENVI source code, there's little that @tboggs or anyone can do to answer questions about differences in results. All you can do is read the implementation of the algorithm in SPy and verify that it's correct (or that it needs to fixed). I'm sure that Thomas would always be happy to have more eyes reviewing the source code.

**Comment by BlcaKHat** [comment]
thanx @tboggs . I will be in touch.
