### ISSUE TITLE
Simple change of warning message (spelling)

### ISSUE THREAD

**Issue by aceisking12** [spectralpython/spectral#96]
I'm using spectral to open files with an envi header. I ran into the following error message:

UserWarning: Parameters with non-lowercase names encountered and converted to lowercase. To retain source file parameter name capitalization, set spectral.setttings.envi_support_nonlowercase_params to True.
  warnings.warn(msg)

You may notice that the warning message has three 't's in settings, and that spectral has no attribute called setttings. Anyway, I thought ya'll would appreciate the heads up.

**Comment by tboggs** [comment]
Oops. Thanks!
